"""Add scheduled_time to SavedSummary

Revision ID: f1bbf1c48b2e
Revises: 0e6536033b2e
Create Date: 2025-04-17 19:07:49.790510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bbf1c48b2e'
down_revision = '0e6536033b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_summary', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###
